### ISSUE TITLE
Reaction Method Spam

### ISSUE THREAD

**Issue by ptmr3** [nigelbro/fluxion#6]
Reaction methods in views are being hit multiple times when the reaction is only emitted once.

The first time the app is run, the reaction will be received once. The second time the app is opened (after hitting onDestroy on the activity), the reaction will be received twice... 3 == 3, 4==4, so on.

**Comment by nigelbro** [comment]
I have found a solution to this i will get a hot fix in this weekend.

**Comment by ptmr3** [comment]
Thanks @nigelbro

**Comment by nigelbro** [comment]
@ptmr3  can you debug for me a bit in your application? I have confirmed that I do have a check in the flux class that checks if the class has already been added to the REACT_CACHE list. So there will never be a time more than one instance would be in the list at a given time.

**Comment by ptmr3** [comment]
I call an action in the onResume of my main fragment. When opening the application, the action gets called once. I have then validated that the action creator method and the store method is hit once. The emit reaction is called once. The react method in the view however is being called multiple times, corresponding to how many times the application has been opened

**Comment by nigelbro** [comment]
Hmm. Thats interesting. The only way this could happen is if this action is being called multiple times or an activity leak . Also I would shy away from calling actions in the onResume of a fragment as it can be called multiple time back to back which would also result in your action to be sent out more than once. The only way for the library to call out the method more than once is if the class is added to the cached ConcurrentMap object more than once. This however can not happen because when any view is added as a reactionSubscriber the method does a REACT_CACHE.containsKey(class) condition which will ignore and not re-add it to the map if it is already added. So at any given time the map only can have one instance of a class and its react annotated methods as you see why its impossible for the library to call the method more than once. which you can see here which is the emitReaction logic
`for(Object parentClass : REACT_CACHE.keySet()) {
					for(Method method : REACT_CACHE.get(parentClass)) {
						if(reaction.getType().equals(method.getAnnotation(React.class).reactionType())) {
							HashMap<String, Object> map = new HashMap<String, Object>();
							map.put(METHOD, method);
							map.put(CLASS, parentClass);
							map.put(REACTION, reaction);
							e.onNext(map);
						}
					}
				}`

**Comment by nigelbro** [comment]
@ptmr3  I added an unregisterAllSubscribers() method that you can call in your main activity onDestroy. This will make certain that the library is not holding on to any context. With this change the library itself can not call the React methods of a class unless by user code. 

build this snapshot compile 'com.github.nigelbro:fluxion:issue_6-SNAPSHOT'

and call the Flux.getInstance().unregisterAllSubscribers() in the main activity on destroy

**Comment by nigelbro** [comment]
fixed in v2.2
